### ISSUE TITLE
Review of tools on usegalaxy.org

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/tools-iuc#1292]
The following is the list of issues and action items for tools currently accessible from usegalaxy.org

----

## Data Sources

- [ ] EBI Only one dataset can be uploaded at a time, making this datasource useless
- [x] BioMart - does not work. **Remove** (galaxyproject/usegalaxy-playbook#33)
- [x] Gramene - does not work. **Remove** (galaxyproject/usegalaxy-playbook#33)
- [ ] modMine - does not have "Export to Galaxy option". Should contact mine people

----

## Collection operation

- [ ] Help sections contain extremely limited information. Need to add images generated by @jmchilton for SAB slides

----

## Text manipulation

- [ ] Concatenate datasets 1.0.0 should be removed and 0.1.0 kept (there are two of them now) (galaxyproject/usegalaxy-playbook#33)
- [x] tac - fix help section (bgruening/galaxytools#601)
- [ ] retain only one `cut` tool (galaxyproject/usegalaxy-playbook#33)

-----

## Fetch sequences and alignments tools

- [ ] Update cached MAF files for hg38, mm10 etc. (there are currently alignments containing hg38)

-----
 
## NGS: QC and manipulation

- [ ]  Select high quality segments - **Remove** (galaxyproject/usegalaxy-playbook#33)
- [x]  Draw quality score boxplot - **Remove** (galaxyproject/usegalaxy-playbook#33)
- [ ]  Barcode splitter - Images do not display in help section
- [ ] Clip adapters - Images do not display in help section
- [ ] Draw nucleotide distribution chart - Images do not display in help section

-----

## NGS: Mapping

- [ ]  Megablast - update databases
- [ ] Map with BWA for Illumina - **Remove** (galaxyproject/usegalaxy-playbook#33)
- [ ] Map with Bowtie for Illumina - **Remove** (galaxyproject/usegalaxy-playbook#33)

-----

## NGS: SAMTools

- [x]  Upgrade to latest SAMTools version

-----

## NGS: BAMTools

- [ ]  BAMTools incorrectly work with dataset collections. If a collection is fed to, for example, Filter tool, it outputs a single dataset (galaxyproject/tools-iuc#1359)

-----

## NGS: Picard

- [x]  Upgrade to latest Picard version

------

## NGS: VCF manipulation

- [x]  Upgrade to latest vcflib version

-----

## NGS: Peak Calling

- [ ] DiffBind - de-uglify help section
- [ ] multiGPS cannot be used in its current form for meaningful analyses. Waiting for overhaul
- [ ] GeneTrack incorrectly packages outputs in a collection (should be a single output file, but it produces a collection) (#1367)

-----

## NGS: RNA Analysis

- [x]  TopHat - **Remove**. HiSat should be spliced mapper we recommend along with STAR, which should be installed on main
- [x] STAR - currently not on main. **Install**
- [x] Filter Combined Transcripts - tool has no meaningful help section. **Remove** (galaxyproject/usegalaxy-playbook#33)
- [x] Tophat Fusion - tool has no help section at all. **Remove**

------

## NGS: Variant Analysis

- [ ] SnpEff download and SnpEff Available Datasets - these two tools circumvent main's cached dataset idea. They allow users to look up and download SnpEff databases. While this relives us from the need to cache these databases this solution feels very hacky. Can the lookup be perfomed dynamically within the SnpEff download tool?
- [ ] SnpEff - update to latest version (2017-03-29)
- [x] Slice VCF - no meaningful help **Remove** (galaxyproject/usegalaxy-playbook#33)

----

## NGS: RNA structure

- [ ] Tools need to be reviewed using new data

-----

## NGS: Gemini

- [ ] Tools need to be reviewed using existing tutorials

----

## NGS: Assembly

- [ ] Trinity - test on Nature Protocols datasets. There are two wrappers: the one of main and another one on iuc by @loraine-gueguen Unfortunately the second one lacks help section completely
- [ ] Spades - **Add**
- [ ] RNASpades - **Add**
- [ ] Unicycler - finish and **Add** (also see test server for more assembly tools in testing)

----

## NGS: Chromosomal Conformation

- [ ] hifive - tool has *very* unresponsive interface - switching options within `Select action to perform` causes significant delay. Needs to be tested with test data and tutorial needs to be written.

-----

## Statistics

- [ ] T Test for Two Samples - help contains errors
- [x] Count GFF Features - no meaningful help **Remove** (galaxyproject/usegalaxy-playbook#33)
- [x] MINE - no meaningful help, incorrectly formatted citation. **Hide** (galaxyproject/usegalaxy-playbook#33)
- [x] Draw ROC plot - no meaningful help. **Hide** (galaxyproject/usegalaxy-playbook#33)
- [x] Draw ROC plot - no meaningful help. **Hide** (galaxyproject/usegalaxy-playbook#33)
- [x] Perform LDA - no meaningful help. **Hide** (galaxyproject/usegalaxy-playbook#33)
- [x] Generate A Matrix - help is not easily translatable mappable onto tool options. **Hide** (galaxyproject/usegalaxy-playbook#33)

-----

## Graph/Display data

- [x] Boxplot of quality statistics - **Remove** (galaxyproject/usegalaxy-playbook#33)

-----
## Phenotype Association and Genome Diversity

- [ ] Tutoruial explaining the use of these tools is absolutely necessary. These tools were written by Webb Miller and Co 

----

## BEDTools

- [ ] Need to be reviewed one by one and updated

----

## Regional Variation, Multiple Regression, Multivariate Analysis, STR-FM

- [ ] For each section create a short tutorial explaining analysis flow through these tools
- [ ] Review tool interfaces and help. In many cases help is rudimentary and citations are not properly formatted

----

## Metagenomics

- [ ] Diamond tools are still not in IUC **Hide**
- [ ] Tutorial explaining vsearch analysis

-----

## NCBI SRA Tools

- [x] The absolute showstopper here is that these tools output paired-end data as interleaved file, which cannot be used by any of downstream Galaxy tools. Needs to be modified to output two files.

**Comment by gregvonkuster** [comment]
>- [ ] multiGPS cannot be used in its current form for meaningful analyses. Waiting for overhaul

This PR https://github.com/galaxyproject/tools-iuc/pull/1227 contains the overhaul.  It has been tested and vetted by @nekrut and myself in a local Galaxy environment and includes functional tests that pass.  The tool requires a Galaxy instance that includes installed chromosome length files in order to function.  The tool results in a valid error if the Galaxy instance does not include installed chromosome length files.  The Galaxy instance used by travis in this repo does not have these chromosome length files installed, which is the reason the functional tests do not pass for the PR.

**Comment by jennaj** [comment]
**Known tool issues**: https://galaxyproject.org/support/tool-issues/ (integration testing for recent fixes in progress - listed a distinct section). 

**Known data issues**: https://galaxyproject.org/support/data-issues/ (needs update per conversation at team mtg with @natefoo and @blankenberg)

**Todo during testing**: cross reference confirmed fixes with items in list above and check-off if complete

**Comment by yhoogstrate** [comment]
@nekrut is this issue superseding issues https://github.com/galaxyproject/tools-iuc/issues/392, https://github.com/galaxyproject/tools-iuc/issues/393, https://github.com/galaxyproject/tools-iuc/issues/396, https://github.com/galaxyproject/tools-iuc/issues/399, https://github.com/galaxyproject/tools-iuc/issues/400 and https://github.com/galaxyproject/tools-iuc/issues/404?

I like including STAR :+1: .

**Comment by martenson** [comment]
@yhoogstrate yes, additionally I am planning to follow through this using the GitHub project here: https://github.com/galaxyproject/tools-iuc/projects/2 where I have already added the remaining items from the issues you linked

**Comment by martenson** [comment]
@nekrut I did not find a new vcflib version we have the latest on Main already

**Comment by jennaj** [comment]
Request to update FastQC https://github.com/galaxyproject/galaxy/issues/4196

**Comment by davebx** [comment]
Interesting, the latest version of fastq_dump ostensibly splits fastq into forward and reverse, but that is only implemented for downloading a list of SRAs from a file. Should be an easy fix.

**Comment by nsoranzo** [comment]
This seems something that should be (and has been already) worked on the https://github.com/galaxyproject/usegalaxy-playbook/ repo
