### ISSUE TITLE
IUC Tools & Collections Hackathon (Fall 2015)

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/tools-iuc#239]
We are planning a remote hackathon on **September 17th and 18th** for Galaxy tool developers to work mainly on dataset collections.

Dataset collections enable MapReduce style workflows in Galaxy and have come a long way over the last year+. Several groups are using dataset collections and newer tools to express workflows of various degrees of complexity that were not possible in Galaxy before.

The remote nature of this gives people who don't have the opportunity to come to GCC hackathons (which have always been productive and a lot of fun) a chance to participate in a Galaxy hackathon. Having a well defined topic will allow us to accomplish a lot and let people who don't have particular tasks in mind find something to work on very quickly.

We are collecting ideas to work on, but we expect to attract the most participation by simply getting tool developers interested in getting help adding collection support to their existing tools and workflows to show up and participate.

If you are interested in participating in the hackathon but not interested in actual tool development - we will assemble a list of smaller, manageable Python and JavaScript tasks to work on and certainly documentation is a chronically lacking for collections so we could use help there and no actual coding would be required.

This is the first remote hackathon we have organized and we encourage ideas or advice about how to organize it please let us know. A core group of will be available on IRC all day and we will have 4 google
hangouts across those days to organize, answer questions, and report progress.

*We will do our best to coordinate and make this hackathon a nice and productive experience and we would like to especially focus on working reasonable hours and discourage overnighters.*

**All forms of contribution are welcome!**

Original idea from @bgruening (https://github.com/galaxyproject/tools-devteam/issues/26#issuecomment-126957869).

# Tools to update:

*Just ideas if these don't make sense remove them*

- [ ] Tophat2 Readgroups (see galaxyproject/tools-devteam#202)
- [ ] bamtools/samtools split should produce collections ([one](https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/bamtools/bamtools_split/bamtools-split.xml), [two](https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/samtools/samtools_split/samtools_split.xml))
- [ ] fastq_paired_end_deinterlacer
- [ ] fastq_paired_end_interlacer
- [ ] fastq_paired_end_joiner
- [ ] fastq_paired_end_splitter
- [x] Trim Galore
- [ ] Trimmomatic (WIP @ https://github.com/fls-bioinformatics-core/galaxy-tools/tree/trimmomatic-add-dataset-collections)
- [ ] other FASTQ trimmers?

# New Tools:

- [ ] Tabular tools (some of this may be covered by unix tools) 
   - [ ] concatenate rows together and add columns for collection identifiers
   - [ ] concatenate columns to a table for each element in a collection (ever a use for this?)
   - [x] Split out a table based on unique values in column (1 table -> collection of tables) [split_file_on_column.xml](https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/split_file_on_column/split_file_on_column.xml) 
- [ ] Tool for concatenating plain textual data (ignoring identifiers I guess)
- [ ] Create a tool that takes in a bam file and produces collection of regions (bed files).
  - [ ] Document a simple workflow that uses this to parallelize work over a bam file in a workflow.
- [ ] Ensure we have sufficient coverage to merge/reduce various other formats.
  - [ ] bam/sam
  - [ ] ...

# general updates
- [x] Replace `<repeats>` where needed with `multiple="True"` in
  - [x] `tools-iuc`
  - [x] `tools-devteam`
  - [x] `galaxytools`
- [ ] migrate the text manipulation tools ([unix-tools](https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/text_processing)) to perform reduce steps

# Documentation:

- [ ] Update planemo collection documentation to include information on creating tools that output collections. Add planemo docs for [BB PR #634](https://bitbucket.org/galaxy/galaxy-central/pull-requests/634/allow-tools-to-explicitly-produce-dataset/diff) and [Git PR #538](https://github.com/galaxyproject/galaxy/pull/538).
- [ ] Document using regions to parallelize work over a bam file in a workflow as a tip in planemo docs.
- [ ] Document using read group macros and general techniques for dealing with read groups in a collection aware fashion in planemo docs. Potentially based off [tools-devteam #103](https://github.com/galaxyproject/tools-devteam/pull/103).
- [ ] Add visual descriptions of various map & reduce operations to planemo documentation.
- [ ] Add end user documentation for using collections in tools. Histories has nice documentation [here](https://wiki.galaxyproject.org/Histories), but I don't think similar documentation exists for tools.

**Comment by bgruening** [comment]
I made a few updates.
@jj-umn @iracooke Do you have time to join and work on proteomic tools?

**Comment by erasche** [comment]
:+1: thanks for creating an issue to track this :)

**Comment by jmchilton** [comment]
Going to send out an announcement to galaxy-dev to drum up support - anyone want to review before I send? I am signing it as IUC so someone from the IUC should probably actually review it :).  https://docs.google.com/document/d/1vXkITrzmZTDWFMDe8__JoqdaK6YBUXxqpbzglapEcqw/edit?usp=sharing

**Comment by erasche** [comment]
@jmchilton awesome! So excited! :)

**Comment by nitesh1989** [comment]
@jmchilton I'm in on this too! Should be fun.

**Comment by bgruening** [comment]
Perfect! Please send it as it is :)

**Comment by jmchilton** [comment]
Sent - http://dev.list.galaxyproject.org/Remote-Hackathon-for-Tools-and-Dataset-Collections-td4667711.html.

**Comment by martenson** [comment]
I am in, obviously.

**Comment by mr-c** [comment]
I'm in!

**Comment by mr-c** [comment]
Can this be a contribution fest instead of a hackathon? I enjoyed Mozilla Science Lab's emphasis on only working what would be ones normal hours, no all nighters..

**Comment by erasche** [comment]
+1 for wording. Most of us already work crazy enough hours and this is to
be friendly/happy/fun collections dev event.

tir. 11. aug. 2015 kl. 18.11 skrev Michael R. Crusoe <
notifications@github.com>:

**Comment by jmchilton** [comment]
Hmm... I have lobbied repeatedly internally to change the hackathon wording for the GCC events. I think a reason to keep the unfortunate hackathon name for this event is to establish some sort of lineage or branding shared between the GCC events and these ones - so I am ``+ .5`` on this change.

@bgruening you first termed this a hackathon (https://github.com/galaxyproject/tools-devteam/issues/26#issuecomment-126957869), any thoughts on change the name?

**Comment by bgruening** [comment]
I guess this is more a cultural thing. For me the word hackathon is associated with a lot of fun, productive work and a nice atmosphere. I would never expect that someone feels urged to participate (after or in normal working hours). People are free to choose and we do not emphasize anything here, at least this was not my attention. It's all about fun, learning and contributing to a project we all love. 
But maybe I'm just too naive here :)

I'm fine with the change if you think it's more appropriate. Codefest is the other possibility from BOSC.

**Comment by mr-c** [comment]
I have lots of positive association with the GCC events I've been at. Alas
in the Bay area it has a quite different connotation. Easy compromise would
be to keep the name but be explicit in the description.

On Wed, Aug 12, 2015 at 6:27 AM Björn Grüning <notifications@github.com>
wrote:

> I guess this is more a cultural thing. For me the word hackathon is
> associated with a lot of fun, productive work and a nice atmosphere. I
> would never expect that someone feels urged to participate (after or in
> normal working hours). People are free to choose and we do not emphasize
> anything here, at least this was not my attention. It's all about fun,
> learning and contributing to a project we all love.
> But maybe I'm just too naive here :)
>
> I'm fine with the change if you think it's more appropriate. Codefest is
> the other possibility from BOSC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-iuc/issues/239#issuecomment-130301169>
> .
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by pvanheus** [comment]
This sounds like a lot of fun - I'm currently in paper-grind mode but will be emerging for air in the nearish future. I've been working on wrappers for the OrthoMCL suite of tools - is anyone else interested in this? (We might switch to using FastOrtho for protein clustering but for now OrthoMCL is the "standard" that we need to wrap).

I prefer the term codefest to hackathon btw.

**Comment by martenson** [comment]
We can call it keyboard-typing-time-together. :)

**Comment by mr-c** [comment]
Has a date been picked?

**Comment by tnabtaf** [comment]
+1 on what Michael just said.

**Comment by jmchilton** [comment]
Sure, let's go with the tenative dates, I wanted to get the Canadians involved but they are busy all month. I'm out for a while, anyone willing to update the description here and add some language about working reasonable hours?

I say we call this one a hackathon, but I'll be sure to continue the discussion.

**Comment by martenson** [comment]
@jmchilton I modified the first post with information from emails and some words about reasonable hours.

**Comment by boratonAJ** [comment]
Ok, I'm in.

**Comment by lparsons** [comment]
Sounds great, it's on my calendar.

**Comment by erasche** [comment]
@tnabtaf could we get this on the calendar please?

**Comment by bgruening** [comment]
@martenson any ideas how to coordinate this? I will be online from 9.00-21.00+ and will try to help wherever I can. Can we use #galaxyproject in freenode or should we use a separate channel?

**Comment by dannon** [comment]
Hangout for tomorrow@10AM EST https://plus.google.com/u/0/events/cnjf2mqg7vl6aigs5fkai6dh4rk

**Comment by mr-c** [comment]
10 AM Eastern _Standard_ Time (UTC−05:00) or Eastern _Daylight_ Time
(UTC−05:00) ?

I think you mean the latter :-)

See y'all tomorrow!

In the past I've been encouraged to send a link to a timezone website like
http://www.timeanddate.com/worldclock/meetingtime.html?iso=20150917&p1=179&p2=3736

**Comment by dannon** [comment]
Yep, I'd already updated it -- gotta read github comments on github and not email, since there's no notification of edits!

**Comment by bgruening** [comment]
Hello everyone!
Today and tomorrow we will try to improve Galaxy tools to consume and create collections. 
You are welcome to join and contribute in any way. For example code contributions, not matter how small, but also in improving documentations and our [best-practice guide](https://github.com/galaxy-iuc/standards).

If you have any questions, suggestions, bugs .... please get in touch with us on:
* IRC (freenode) #galaxyproject 
* [permanent hangout](https://talkgadget.google.com/hangouts/_/qm45a5itqh25uod7umceeyrrcua) (not sure if this will scale)
* our *Session I* hangout at @10AM EDT https://plus.google.com/u/0/events/cnjf2mqg7vl6aigs5fkai6dh4rk

I would also like to start a proper documentation about collections and collect tips in [this document](https://docs.google.com/document/d/1UanoJvhaM2r8kN_onHB5tmum1OMupThHXvuts2rzCqA/edit?usp=sharing) with the aim to move parts of it back into the tool documentation as well as the best-practice guide.

Have a lot of fun!
Bjoern

**Comment by Public-Health-Bioinformatics** [comment]
Just a note that now I'm doing a quality control tool that touches on the extraction of log/job status data from workflow log files, for reporting and to trigger stop/error states.  Runs off of a list of rules (predefined text-mining functions like regex etc. applied to specific log files to create temp variables and final report outputs in json format).  May be of interest to others?

**Comment by bgruening** [comment]
@Public-Health-Bioinformatics sounds interesting, but I don't think I fully understand it :)

Coders: The second trimmer is updated and ready for a review: https://github.com/bgruening/galaxytools/pull/245

**Comment by erasche** [comment]
@Public-Health-Bioinformatics might be useful in the (recently added) advanced exit code detection routines in galaxy. Can link information tomorrow.

**Comment by bgruening** [comment]
The second day of our Codefest has begun. Anyone wants to work on the new tools? It should be possible to implement them with standard unix tools and a little bit of collection magic! :)

**Comment by erasche** [comment]
I'll claim swapping out repeats with multiple="True".

**Comment by bgruening** [comment]
@jmchilton is this suiteable to check off the "Tool for concatenating plain textual data (ignoring identifiers I guess)" item?
https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/cat.xml

**Comment by pvanheus** [comment]
This is the PR for the work we did at SANBI-SA: https://github.com/galaxyproject/tools-devteam/pull/227 and blog with a little documentation http://pvh.wp.sanbi.ac.za/2015/09/18/adventures-in-galaxy-output-collections/

@Public-Health-Bioinformatics sounds interesting, Jen specifically mentioned at GCC 2015 that she'd like to be able to decide whether a workflow can continue or should abort based on quality control, perhaps your work feeds into this goal.

**Comment by pvanheus** [comment]
And now... what next? Is there a wrap-up for the codefest planned? If so, who is writing it? And when's the next one?

**Comment by bgruening** [comment]
@jmchilton is this suiteable to check off the "Tool for concatenating plain textual data (ignoring identifiers I guess)" item?
https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/cat.xml

**Comment by bgruening** [comment]
@pvanheus I will try to collect all PR and write a small summary here. If I can get more time to devote to this I will try to do this kind of events more regularly. Maybe every two month?

**Comment by Public-Health-Bioinformatics** [comment]
@erasche You mentioned "advanced exit code detection routines in galaxy."  I would like more info on that.  My QC tool basically lets one set up rules that trigger whether to stop a job or continue, as well as reporting on QC metrics.  I'm now at the point where I need to code the stop a job part.  Assuming its just a matter of exit code 1, but if you folks have some new options or things to understand I'd like to learn.

Thanks,

Damion

**Comment by erasche** [comment]
@Public-Health-Bioinformatics sorry, I knew there was someone I was supposed to forward documentation to, my apologies. https://github.com/galaxyproject/galaxy/pull/117 implemented functionality that provided an easier alternative to the exit code detection stuff. You simply add the `detect_errors="..."` to your `<command/>` block, like in [this example](https://github.com/galaxyproject/galaxy/pull/117/files#diff-04877581ccca2c24654dd0d828cc1c98R2) and that replaces doing it [the old way with regex](https://github.com/galaxyproject/tools-iuc/blob/master/tools/bedtools/macros.xml#L10)

**Comment by nsoranzo** [comment]
Final report for the Codefest: https://wiki.galaxyproject.org/News/IUCCollectionsCodefest
