### ISSUE TITLE
IUC Packaging TODO List

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#33]
In the interests of tracking things which we want to package or see included, here's a TODO list analogous to galaxyproject's trello cards and voting.

- [ ] PacBio Tools
  - I have progress on BLASR, and somewhere on my hard drive I had a first stab at converting their workflows to galaxy JSON workflows. Just message me (@erasche) for them.
- [ ] [RAMPART](https://github.com/TGAC/RAMPART)
- [ ] [Circos](http://circos.ca)
  - In progress
- [ ] FFMpeg for microscopy video data.
- [ ] ImageMagick's `convert` for imaging data

Please feel free to add packages to this list and check them off whenever they get completed!

**Comment by jj-umn** [comment]
@erasche I would be interested in seeing what you've done with PacBio.  
Is any interested in HISAT?  I made a package tool_dependencies.xml, a data_manager, and was about 75% to a tool wrapper.

**Comment by erasche** [comment]
@jj-umn my packages/wrappers are [here](https://github.com/erasche/galaxy-tools/tree/master/PacBio). The PacBio one had some glaring bugs which I've fixed locally, I'll push those shortly.

**Comment by erasche** [comment]
@jj-umn pushed PacBio stuff [here](https://github.com/galaxyproject/tools-iuc/tree/pacbio). BLASR works for fasta files. 


- datatypes aren't written yet and need to be to handle the directories of .ba(s|x).h5 files on disk
- As a result, none the hdf5 stuff is working yet
- packages are untested, they're probably all broken.

**Comment by erasche** [comment]
@jmchilton had suggestion of putting together a yearly paper mentioning everything the @galaxyproject/iuc has wrapped in the past N months.

**Comment by erasche** [comment]
Mentioned QuickGO xref #6 for onto-viz.

**Comment by bgruening** [comment]
@erasche does this count? https://github.com/bgruening/galaxytools/tree/master/tools/image_processing/image_processing

**Comment by erasche** [comment]
@bgruening yes, that was what was originally linked by the "progress..." comment. Will update the link in a bit since you've reorganised your repo.

**Comment by erasche** [comment]
More tools to convert (I need BER) https://github.com/jorvis/ergatis/tree/master/components

I didn't know a tool wrapping format could be less friendly than Galaxy ;)

**Comment by yhoogstrate** [comment]
CrossMap (http://www.ncbi.nlm.nih.gov/pubmed/24351709) is a free (GPLv2) tool similar to liftover from UCSC, but supports more file formats, including VCF.

The url to the sourcecode given in the article is not available anymore, but is available at: http://sourceforge.net/projects/crossmap/files/
