### ISSUE TITLE
'Le Big' Main Winter Cleanup

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#488]
# requires installation/uninstallation
- [x] install datamash tools into their own section (reverse, transpose, datamash)
- [x] install trimmomatic, trim galore, pear 
- [x] update BWA and MEM
- [x] RNA analysis to MAIN except of trinity
- [x] sam tools merge to MAIN except call and phase
- [x] NVC, freebayes, varian annotator latest to MAIN
- [x] variant analysis  merge into MAIN without GEMINI
- [x] chipseq to MAIN + bamfilter
- [x] bedtools to MAIN
- [x] statistics merge into MAIN
- [x] multivariate analysis section mirror test to MAIN
- [x] multiple regression section mirror test to MAIN
- [x] graph section: merge into MAIN
- [x] install str_fm microsat analysis (https://github.com/Arkarachai/STR-FM)
- [x] metagenomics: skip diamond, propagate rest, deprecate what is on Main, 
- [x] NGS: DuNovo propagate to MAIN (resource selector ping @natefoo )
- [x] add MEME to motif section (https://github.com/galaxyproject/tools-iuc/pull/478) 
- [x] MAFFT to multiple alignment section
- [x] install HISAT2 on MAIN

# tooldev related
- [x] fix help on sailfish https://github.com/bgruening/galaxytools/pull/283
- [ ] test HISAT2 @nekrut
- [ ] fix heatmap tool images https://github.com/galaxyproject/tools-iuc/issues/495

# org related
- [x] mutate codons  to variant analysis
- [x] variant analysis out of BETA
- [x] move extract feature section to operate on gen intervals
- [x] combine fetch section into one
- [x] ask about sed/awk security issues (@natefoo)
- [x] tab to fastq and fastq to tab move to convert section from NGS QC (there are more like this, review)
- [x] histogram move to graph display data (remove form filter)
- [x] get genomic scores move to operate on genomic intervals section
- [x] remove ngs toolbox beta
- [x] introduce DEPRECATED section
- [x] make old picard disappear
- [x] make GATK deprecated
- [x] section CloudMap and move CloudMap tools there
- [x] group all NGS sections next to each other
- [x] remove `RNA STRUCTURE PREDICTION` label
- [x] hide old snpeff tools

# DM installed on Test
- [x] HISAT2
- [x] bowtie
- [x] bowtie2

# reference data and indexes
tracked at https://github.com/galaxyproject/galaxy/issues/1470

# problems
 - [x] sailfish cannot install its dependency, cmake (timeout)
 - [ ] unable to install deeptools (even on Test)
 - [x] other sailfish issues https://github.com/bgruening/galaxytools/issues/284
 - [x] update bamtools - needs some DB fixing (https://github.com/galaxyproject/galaxy/issues/1390)
 - [ ] sailfish DM has incorrect dependencies
 - [ ] sailfish indexes (see above)

**Comment by nekrut** [comment]
GEMINI should follow shortly once it works on test for @bgruening and me

**Comment by bgruening** [comment]
* @natefoo @martenson regading security: https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/text_processing#note-about-security
* @deeptools 2.0 will be released this year
* HISAT2 not HISAT, we should deprecate HISAT
@nekrut working on a new gemini release: https://github.com/galaxyproject/tools-iuc/tree/gemini but the old one is working for us here
* @nekrut diamond not good enough (just interested, I don't have a string feeling here)

**Comment by natefoo** [comment]
I concur with @bgruening regarding the security.

@nekrut, which resource selector did you want on Main? Right now the tools that can go to Stampede get a selector for that (and also for the "test/development" queue).

**Comment by martenson** [comment]
thanks @natefoo @bgruening !

**Comment by martenson** [comment]
@davebx could you please fix images on https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/guru-ananda/heatmap/heatmap_1/1.0.0
thanks!

**Comment by natefoo** [comment]
'Le Grand'?

**Comment by martenson** [comment]
too French

**Comment by martenson** [comment]
created issue for the heatmap tool in iuc repo
https://github.com/galaxyproject/tools-iuc/issues/495

**Comment by martenson** [comment]
This is mostly done, see the checklist.

**Comment by bgruening** [comment]
This is amazing! usegalaxy.org will rock even harder! Thanks @martenson!

**Comment by jennaj** [comment]
**HISAT2 DM** has a problem with advanced options re SNP annotation. See: unrecognized arguments

> Fatal error: Exit code 2 ()
> usage: extract_snps.py [-h] [-v] [--testset] [genome_file] [snp_file]
> extract_snps.py: error: unrecognized arguments: --genome_file --snp_file snps.tabular

**Comment by martenson** [comment]
@jennaj please create a new issue for that

**Comment by jennaj** [comment]
@martenson Done, thanks! https://github.com/galaxyproject/tools-iuc/issues/530

**Comment by martenson** [comment]
I added bunch of labels to `new` and `updated` tools on Main. I probably missed some. Let me know if something is missing/wrong.
