### ISSUE TITLE
Roadmap: JBrowse

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#508]
# Changelog / Upcoming Changes

## v0.5
- [x] update existing jbrowse instances on disk (adding new tracks, also support pulling info from apollo) f4206bc58448bb39e5fae31942477c45642a9fca
- [x] generate-names.pl http://gmod.org/wiki/JBrowse_Configuration_Guide#Name_Searching_and_Autocompletion
- [x] Allow forcing HTML rather than canvas ef1646fc375513143fd743841ac618720267dbc9
- [x] defaultTracks e6ef382e885381ab1606e44f397477014434aa82
- [x] http://gmod.org/wiki/JBrowse_Configuration_Guide#General_configuration_options acb5b6696880d517bf76b790e70496b714dd46c3, f93e44ee9cc01d2f83ccbfe7151b408c12d4b333
- [x] Bugfix: >12 sequences would exceed brewer colour limit and crash. Now cycles back to start. https://github.com/galaxyproject/tools-iuc/commit/3dadcef329a8881837293e354b21880a6ecd3ca9
- [x] Bugfix: Incorrect XML could be generated, causing a crash for automatically coloured, automatically scored bigwig tracks 2fd44398452799138fa5c95fa78996814c72d386
- [x] Bugfix: BlastXML tracks without a gff3 feature parent would crash. 4be3385

## v0.6

- [x] log support for bigwig tracks
- [x] REST endpoints
- [x] Accept data from chrom/len files, and from data tables
- [x] templated values in name / text field. E.g. ability to use "#date#" to get a dated category. Useful when updating pre-existing JBrowses with re-run analyses.
- [x] track metadata
- [x] Conda packages

## v0.7

- [x] Editing menus
- [x] Plugins
  - [x] https://github.com/cmdcolin/gccontent
  - [x] https://github.com/Arabidopsis-Information-Portal/ComboTrackSelector
- [x] Themes

## v0.8+

- [x] SPARQL endpoints
- [ ] more JBrowse plugins! (Specifically the one that links db_xrefs to upstream databases, such as IPR:000000 -> `http://....`)
  - [x] https://github.com/cmdcolin/multibigwig
  - [ ] https://github.com/cmdcolin/sashimiplot
- [ ] disable left-click action
- [ ] auto create blat?
- [ ] ... ? Ideas?
- [ ] enhance compat with blast XML data
- [ ] full support for protein files
  - [ ] fix chrom selector upstream
  - [x] css rules upstream
- [ ] support blast tabular data in 12 and 24 column variants

## v1.0

Some of these may get shifted around as time and requirements dictate

# Changelog

**Comment by jjkoehorst** [comment]
SPARQL endpoints, would this also include plain text rdf files in the galaxy history? Which can perhaps be loaded into a temporarily RDF endpoint or through HDT files?

**Comment by erasche** [comment]
@jjkoehorst meant to get sparql done earlier, but GCC snuck up on me.

I imagine that this would be possible. A plain text RDF would just be a read-only data store? Hmm. I think I can give you a better answer once I've gotten the SPARQL portion done. Hopefully soon... I demoed a heavily dockerized, heavily interconnected GMOD stack today and would love to add sparql export to a lot of places.

**Comment by jjkoehorst** [comment]
@erasche no worries, glad it is still on the map! A plain text RDF (Turtle/N3/RDFXML, etc) could be a read only store but requires loading into a memory or disk store (jena/sparqlwrapper/blazegraph). However if jbrowse would support update queries, if that is what you mean, that would be even more amazing but probably a bridge to far?...

HDT is a binary disk image. I have been looking into JENA but this creates multiple index files which is not suitable for galaxy history (I think) and currently using blaze graph which creates a single index file.  

Most importantly at least from my point of view would be the ability to create predefined (and modify) SPARQL queries for jbrowse views. As yes there are some kind of ontologies for storing locations but not everything is suitable at all times.

**Comment by bernt-matthias** [comment]
Seems that the issue can be closed since now 1.16.5 is already wrapped

**Comment by erasche** [comment]
Hey @bernt-matthias, this is just a roadmap issue, not tied to a specific release. I've been leaving it open so we can track requests we get for galaxy-jbrowse features without filling new issues / making noise every time. If the IUC has a better way to do that, I'm happy to move it there. Currently there are still a number of open TODOs on this one that I'd like to keep track of.

**Comment by erasche** [comment]
bug: can't use the same bigwig twice due to symlink behaviour. replace with cp?

```
ln: failed to create symbolic link ‘data/raw/5302296cad2d7c9d5f1a73751b42aa68_0.bw’: File exists
```

**Comment by jennaj** [comment]
Hi @hexylena 

If you want this in a distinct ticket, lmk, will move it. 

We (@dannon & @mvdbeek) were wondering if there was a way to adjust Jbrowse to be able run in anonymous (not logged in) sessions. Currently, there is a dependency requiring the "user email" to access a genome input from history. If not logged in, this fails the tool, immediately. 

Or, maybe login should be required (and if not logged in, report that back to the user in the read error dataset, maybe in job info & stderr? so shows up in dataset itself and bug reporting preview). "You must be logged in to use this tool" or similar. 

This may be complicated to do -- options like "JBrowse-in-Galaxy Action" > "Update existing ..." might be bothersome. Unless prior sessions all linked back that same anon history's datasets Ok.

The test example comes from this GTN tutorial: https://training.galaxyproject.org/training-material/topics/visualisation/tutorials/jbrowse/tutorial.html

Tested it as not logged in originally vs logged in from start, just to compare (at .org). Just did the not-logged-in-first at .eu. Same result -- only not being logged in _during actual tool execution_ triggers the failure: 
* https://usegalaxy.org/u/jen/h/test-jbrowse----originally-not-logged-in
* https://usegalaxy.org/u/jen/h/test-jbrowse----originally-logged-in
* https://usegalaxy.eu/u/jenj/h/test-jbrowse----originally-not-logged-in 

Clicking not the "eye" icon (logged in, successful run, give an additional pop-up warning at .eu (don't show up at .org). It doesn't seem to impact the viz through. Or, I'm not sure what to look for.

<img width="152" alt="Screen Shot 2020-04-23 at 1 12 57 PM" src="https://user-images.githubusercontent.com/8999735/80145929-d631cb00-8565-11ea-8f7f-f5d74f5c64e5.png">

The message displayed in the red error dataset is a bit different between the two servers as well. Eu is more informative.  

org: `cannot find 'email'`
eu: `cannot find 'email' while searching for 'reference_genome.genome.history.user.email'`

This shows up at both servers, in the bug report. Is a bug have seen in a few other tool, not sure where it is coming from exactly. The inputs are not duplicated :)

```
Detected Common Potential Problems
The tool was executed with one or more duplicate input datasets. This frequently results in tool errors due to problematic input choices.
```

Full traceback from org (bug report sent into myself :). The job details > stderr & stdout reports at both servers are empty. (Expected, given bug report contents). 

```
tool id: toolshed.g2.bx.psu.edu/repos/iuc/jbrowse/jbrowse/1.16.8+galaxy0
tool version: 1.16.8+galaxy0
job pid or drm id: None
job tool version: None
-----------------------------------------------------------------------------
job command line:
None
-----------------------------------------------------------------------------
job stderr:

-----------------------------------------------------------------------------
job stdout:

-----------------------------------------------------------------------------
job info:
cannot find 'email'
-----------------------------------------------------------------------------
job traceback:
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 231, in _valueForName
    nextObj = getattr(obj, key)
AttributeError: 'NoneType' object has no attribute 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/__init__.py", line 1049, in unicodify
    value = text_type(value)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1587388900_1572237_44025.py", line 133, in respond
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 292, in valueFromSearchList
    executeCallables=executeCallables)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    _raiseNotFoundException(key, obj)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 178, in _raiseNotFoundException
    raise NotFound(excString)
Cheetah.NameMapper.NotFound: cannot find 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 231, in _valueForName
    nextObj = getattr(obj, key)
AttributeError: 'NoneType' object has no attribute 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/__init__.py", line 1051, in unicodify
    value = str(value)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1587388900_1572237_44025.py", line 133, in respond
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 292, in valueFromSearchList
    executeCallables=executeCallables)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    _raiseNotFoundException(key, obj)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 178, in _raiseNotFoundException
    raise NotFound(excString)
Cheetah.NameMapper.NotFound: cannot find 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 231, in _valueForName
    nextObj = getattr(obj, key)
AttributeError: 'NoneType' object has no attribute 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 236, in prepare_job
    job_wrapper.prepare()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 1085, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 462, in build
    raise e
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 458, in build
    self.__build_config_files()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 533, in __build_config_files
    self.__write_workdir_file(config_filename, config_text, param_dict, is_template=is_template)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 616, in __write_workdir_file
    value = fill_template(content, context=context, python_template_version=self.tool.python_template_version)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/template.py", line 94, in fill_template
    raise first_exception or e
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/template.py", line 67, in fill_template
    return unicodify(t)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/__init__.py", line 1057, in unicodify
    msg = "Value '%s' could not be coerced to Unicode" % value
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1587388900_1572237_44025.py", line 133, in respond
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 292, in valueFromSearchList
    executeCallables=executeCallables)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 233, in _valueForName
    _raiseNotFoundException(key, obj)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 178, in _raiseNotFoundException
    raise NotFound(excString)
Cheetah.NameMapper.NotFound: cannot find 'email'
```

**Comment by hexylena** [comment]
Hi @jennaj sure, we can fix that. It was never to intentionally exclude anonymous users, I just totally forgot they exit :joy:, easy fix though.

"Error reading from name store" - know bug, never figured out how to solve it unfortunately.
