### ISSUE TITLE
IUC Codefest - Conda dependencies

### ISSUE THREAD

**Issue by remimarenco** [galaxyproject/tools-iuc#700]
On monday 04/04, @bgruening and some members of Galaxy team (me and @nitesh1989 at least) would want to get a Codefest on adding IUC / Devteam tools Conda dependencies.

Hackathon begins at: 10am (UTC-4) / 4pm (UTC+2).

Hangout link: https://hangouts.google.com/call/xp6vucjka5bj7pq53uoohol6zie

It will be as following:

- [x] @bgruening will give a small introduction how to create a recipe and the scripts involved in it]
- [x] Introduce everyone to conda and bioconda
- [x] Then we pick a simple tool and create it
- [x] @bgruening will provide a list with bugs that needs to be fixed on the framework level

Aims:
* get familiar with conda packaging the conda-Galaxy integration
* remove tools from the testing blacklists: [1](https://github.com/galaxyproject/tools-iuc/blob/master/.tt_blacklist) [2](https://github.com/galaxyproject/tools-devteam/blob/master/.tt_blacklist) [3](https://github.com/bgruening/galaxytools/blob/master/.tt_blacklist)
* Integrate Travis-conda testing in GalaxyP
* Integrate Travis-conda testing in galaxy_blast (@peterjc?)

Infrastructure work:
* https://github.com/galaxyproject/galaxy/issues/2047
* condarc is update if you add new channels, but you can not remove channels
* conda is not working in the Galaxy Docker image
* bioconda needs to archive all tarballs to depot.galaxyproject.org
* Galaxy Admin support to remove environments

Tools to convert (for beginners):
* [ ] raxml
* [ ] vegan
* [x] seqtk
* [ ] bcftools - [WIP Tools-IUC #707 ](https://github.com/galaxyproject/tools-iuc/pull/707)
* [ ] art - [WIP Tools-IUC #709](https://github.com/galaxyproject/tools-iuc/pull/709)
* [ ] macs2 - [WIP Tools-IUC #710](https://github.com/galaxyproject/tools-iuc/pull/710)
* [ ] diamond
* [ ] crossmap - https://github.com/galaxyproject/tools-iuc/pull/702
* [ ] STAR-Fusion - https://github.com/galaxyproject/tools-iuc/pull/704

Conda packages to create (for beginners):
* [ ] PileOMeth (C/C++)
* [x] bamhash - [WIP BioConda Recipes #1196](https://github.com/bioconda/bioconda-recipes/pull/1196)
* [ ] openms
* [ ] imagej2 (Java)
* [x] find_subsequences => Biopython is available in [Conda](https://anaconda.org/search?q=biopython), see https://github.com/bgruening/galaxytools/pull/329 
* [ ] all tools under tools/rna_tools/ (C/C++)

Let us know if you are interested!

**Comment by remimarenco** [comment]
I changed the time of this. I guess that would be better for everybody :)

**Comment by bgruening** [comment]
I have collected a few tools and dependencies that should be a good start.

**Comment by remimarenco** [comment]
Thanks @bgruening !

**Comment by yhoogstrate** [comment]
I have once written a extensive wrapper for CrossMap but I got into problems with all the dependencies. However, using conda as dependency resolver might quickly solve the issue and make the wrapper usable. Maybe we could add it to the list?

**Comment by bgruening** [comment]
@yhoogstrate I added it to the simple section as bioconda already as a package for it :)

**Comment by yhoogstrate** [comment]
I saw you worked on that :+1: awesome

**Comment by bgruening** [comment]
@yhoogstrate if you want create a WIP PR with this wrapper and we can try to make testing pass with the conda package.

**Comment by remimarenco** [comment]
Summary of the Hackathon is available here: https://docs.google.com/document/d/1qvH4XzFG1wyvW_42VTnEol3Pi-wiSmGwOrhSOmMz3J8/edit

**Comment by remimarenco** [comment]
@bgruening For bcftools, am I wrong by saying the requirement is the same than the existing one? (https://github.com/galaxyproject/tools-iuc/blob/master/tools/bcftools/macros.xml)

Do we have something else to add?

**Comment by bgruening** [comment]
No this is correct. But to trigger a test you still need to remove the line from the blacklist and you need to change somehow the XML file. This is because travis only test tools that have changed. Tweak some styles on the XML, improve the help ... these kind of changes.

**Comment by bgruening** [comment]
@remimarenco can we close this? We should do a second one I guess before GCC and finish a few more tools as well as update the documentation.

**Comment by remimarenco** [comment]
Sure no problem :)
