### ISSUE TITLE
Issues discovered from whole git repo push to TTS

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#88]
## Round 1

- [x] package_biopython_1_61 contains a readme.rst (fc79e42ba3054c9f440660642069c708344440ad)
- [x] package_dill_0.2 has a period (006abbf1447439b8fdfb727be5651ffdc1d91690)
- [x] package_faToTwoBit_35x1 has uppercase letters (same for gfClient/gfServer) (5fa42e48613d63af1a10cecf998f07837fca7ef4, 2b256a8b2db84063dfdf376423c6799b15f59317, 3db286e3e982fc0c88d36bad7a3aca0b771a3246)
- [x] package_graphclust_0_7_6 has invalid XML (53172da)
- [x] package_tabix had bad yaml (https://github.com/galaxyproject/tools-iuc/commit/f04f0996c5b20cbd8842678ab7b34202a26e48e9)
- [x] package_ballgown_1_0_3 is missing a description
- [x] tools/gemini had invalid YAML (https://github.com/galaxyproject/tools-iuc/commit/21965f91d06439c05db1b00780d61f3a6db904f4)
- [x] package_samtools_0_1_18 missing description (afa04146f90af65c11c859532c2de8f0c210738f)
- [x] package_samtools_0_1_16 missing description (afa04146f90af65c11c859532c2de8f0c210738f)
- [x] package_samtools_0_1_2 missing description (afa04146f90af65c11c859532c2de8f0c210738f)
- [x] package_ucsc_tools_0_1 missing description (ec17626cdef4998ce0da4f0073d9658d88908d2c)
- [x] tool_factory_2 has invalid dependency on `package_graphicsmagick_1_3_20` and owner `iuc`. #90, #89

## Round 2

- [x] tool_factory_2: "Could not find repository in toolshed" then "You already own a repository named tool_factory_2, please choose a different name" (#97)
- [x] snpsift_* depend on snpsift_dbnsfp_datatypes repository, which isn't in TTS. (#95)

Other than that we're good. I'll probably handle some of the above tomorrow.

CC @bgruening @martenson

**Comment by bgruening** [comment]
Will fix it now!

**Comment by erasche** [comment]
You want to add the misisng descriptions? I've got most of the others...

**Comment by erasche** [comment]
I'm working in the branch `88fixes` if you want to add there

**Comment by erasche** [comment]
Oooh this is going to be a fun merge. Let me know when you're done @bgruening and I'll rebase + merge fixes.

**Comment by erasche** [comment]
Pushing all to TTS from command line manually, things look good so far!

**Comment by bgruening** [comment]
muchas gracias

**Comment by erasche** [comment]
de rien~

**Comment by erasche** [comment]
Added round 2 changes. We're mostly at parity between IUC GitHub and TTS now.
